array_width = 0
attr_fn_like_width = 0
fn_call_width = 100
hard_tabs = true
max_width = 100
newline_style = "Unix"
short_array_element_width_threshold = 0
single_line_if_else_max_width = 0
single_line_let_else_max_width = 0
struct_lit_width = 0
struct_variant_width = 0
use_small_heuristics = "Off"

# Unstable features.
unstable_features = true

comment_width = 100
error_on_line_overflow = true
force_multiline_blocks = true
format_code_in_doc_comments = true
group_imports = "StdExternalCrate"
imports_granularity = "Item"
imports_layout = "Horizontal"
inline_attribute_width = 0
struct_lit_single_line = false
wrap_comments = true
