[package]
name = "regen-src"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
rustdoc-types = "0.30.0"
serde_json = "1.0.128"
serde = "1.0"
thiserror = { workspace = true }
